"""新增user和collaborator_invites表

Revision ID: d2b4f837ae93
Revises: 
Create Date: 2026-06-01 10:05:09.108600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2b4f837ae93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('count')
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.alter_column('create_time',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('update_time',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('creator_id')

    op.create_table('count',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
